//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Modelo_dadosContainer : DbContext
    {
        public Modelo_dadosContainer()
            : base("name=Modelo_dadosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jogador> JogadorSet { get; set; }
        public virtual DbSet<Amigos> AmigosSet { get; set; }
        public virtual DbSet<Campo> CampoSet { get; set; }
        public virtual DbSet<Posicao> PosicaoSet { get; set; }
        public virtual DbSet<JogadorPosicao> JogadorPosicaoSet { get; set; }
        public virtual DbSet<Time> TimeSet { get; set; }
        public virtual DbSet<JogadoresTime> JogadoresTimeSet { get; set; }
    }
}
