//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Time()
        {
            this.JogadoresTime = new HashSet<JogadoresTime>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int CampoId { get; set; }
        public int Jogador_proprietarioId { get; set; }
    
        public virtual Campo Campo { get; set; }
        public virtual Jogador JogadorProprietario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JogadoresTime> JogadoresTime { get; set; }
    }
}
